package com.matrixmulti;

import java.io.IOException;

import org.apache.hadoop.io.IntWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Mapper;

/*
Mapper<KEYIN,VALUEIN,KEYOUT,VALUEOUT>
IntWritable - Key generated by Hadoop
Text - The matrix itself
Text - The output matrix position (e.g. "(0,0)")
Text - "(Matrix filename, value)"
 */
public class MatrixMapper extends Mapper<IntWritable, Text, Text, Text> {
    @Override
    public void map(IntWritable key, Text col, Context context) throws IOException, InterruptedException {
        String filename = context.getInputSplit().getClass().getName();
        String[] value = col.toString().split(",");
        for (String val : value) {
            context.write(new Text(filename), new Text(val));
        }
    }
}
